export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE ='CHANGE_MESSAGE';
export const DELETE_CART ='DELETE_CART';
export const UPDDATE_ADD_CART='UPDDATE_ADD_CART';
export const UPDDATE_REMOVE_CART='UPDDATE_REMOVE_CART';

